### ISSUE TITLE
Error creating Testharness - "Error finding pid for bisq-BTC_REGTEST_Arb_dao"

### ISSUE THREAD

**Issue by haas-ac** [ghubstan/bisq-api-reference#17]
Hi
i followed this guide: https://github.com/bisq-network/bisq/blob/master/apitest/docs/api-beta-test-guide.md
to set up a test environment for the Bisq-API.  

When executing the command to set up the different daemons I get the following error: 

https://pastebin.mozilla.org/SwtJOpUd 

```
$ ./bisq-apitest --apiPassword=xyz \
        --supportingApps=bitcoind,seednode,arbdaemon,alicedaemon,bobdaemon \
        --shutdownAfterTests=false
```
```
Feb-13 15:45:37.624 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcVersionService.io.bisq.protobuffer.GetVersion/GetVersion (1/1000ms). 
Feb-13 15:45:37.641 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcDisputeAgentsService.io.bisq.protobuffer.DisputeAgents/RegisterDisputeAgent (10/1000ms). 
Feb-13 15:45:37.642 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcGetTradeStatisticsService.disabled (1/1ms). 
Feb-13 15:45:37.642 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcHelpService.disabled (1/1ms). 
Feb-13 15:45:37.642 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcOffersService.disabled (1/1ms). 
Feb-13 15:45:37.642 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcPaymentAccountsService.disabled (1/1ms). 
Feb-13 15:45:37.643 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcPriceService.disabled (1/1ms). 
Feb-13 15:45:37.643 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcTradesService.disabled (1/1ms). 
Feb-13 15:45:37.643 [main] INFO  b.d.g.i.GrpcServiceRateMeteringConfig: Adding call rate metering definition GrpcWalletsService.disabled (1/1ms). 
Feb-13 15:45:37.693 [main] INFO  bisq.apitest.ApiTestMain: Configuring test harness with options:
	--apiPassword=xyz
	--supportingApps=bitcoind,seednode,arbdaemon,alicedaemon,bobdaemon
	--shutdownAfterTests=false
	--callRateMeteringConfigPath=/tmp/ratemeters.json 
Feb-13 15:45:37.719 [main] INFO  bisq.apitest.Scaffold: Cleaning dao-setup data in /home/serveradmin/api-beta-test/apitest/build/resources/main 
Feb-13 15:45:37.875 [main] INFO  bisq.apitest.Scaffold: Installed /home/serveradmin/api-beta-test/apitest/src/main/resources/dao-setup/bisq-BTC_REGTEST_Alice_dao/ratemeters.json with perms rwx------. 
Feb-13 15:45:37.887 [main] INFO  bisq.apitest.Scaffold: Installed /home/serveradmin/api-beta-test/apitest/src/main/resources/dao-setup/bisq-BTC_REGTEST_Bob_dao/ratemeters.json with perms rwx------. 
Feb-13 15:45:37.893 [main] INFO  bisq.apitest.Scaffold: Copied all dao-setup files to /home/serveradmin/api-beta-test/apitest/build/resources/main 
Feb-13 15:45:37.899 [main] INFO  bisq.apitest.Scaffold: Installed /home/serveradmin/api-beta-test/apitest/build/resources/main/Bitcoin-regtest/blocknotify with perms rwx------. 
Feb-13 15:45:37.900 [main] INFO  bisq.apitest.Scaffold: Starting supporting apps [bitcoind, seednode, arbdaemon, alicedaemon, bobdaemon] 
Feb-13 15:45:37.905 [main] INFO  b.a.linux.AbstractLinuxProcess: Checking bitcoind env...
	berkeleyDbLibPath   
	bitcoinPath         /usr/local/bin
	bitcoinDatadir      /home/serveradmin/api-beta-test/apitest/build/resources/main/Bitcoin-regtest
	blocknotify         /home/serveradmin/api-beta-test/apitest/build/resources/main/Bitcoin-regtest/blocknotify 
Feb-13 15:45:38.073 [pool-1-thread-1] INFO  b.apitest.linux.BitcoinDaemon: Starting ...
$ /usr/local/bin/bitcoind -datadir=/home/serveradmin/api-beta-test/apitest/build/resources/main/Bitcoin-regtest -daemon -regtest=1 -server=1 -peerbloomfilters=1 -debug=net -fallbackfee=0.0002 -rpcport=19443 -rpcuser=apitest -rpcpassword=apitest -blocknotify="/home/serveradmin/api-beta-test/apitest/build/resources/main/Bitcoin-regtest/blocknotify %s" 
Feb-13 15:45:42.974 [main] INFO  bisq.apitest.Scaffold: Giving 5000 ms for bisq-BTC_REGTEST_Seed_2002 to initialize ... 
Feb-13 15:45:43.002 [pool-1-thread-2] INFO  bisq.apitest.linux.BisqProcess: Starting bisq-seednode -> bisq-BTC_REGTEST_Seed_2002 ...
$ export JAVA_OPTS="-XX:MaxRAM=2g -Dlogback.configurationFile=apitest/build/resources/main/logback.xml";  /home/serveradmin/api-beta-test/bisq-seednode --appName=bisq-BTC_REGTEST_Seed_2002 --appDataDir=/home/serveradmin/api-beta-test/apitest/build/resources/main/bisq-BTC_REGTEST_Seed_2002 --nodePort=2002 --rpcBlockNotificationPort=5120 --rpcUser=apitest --rpcPassword=apitest --rpcPort=19443 --daoActivated=true --fullDaoNode=true --seedNodes=localhost:2002 --baseCurrencyNetwork=BTC_REGTEST --useDevPrivilegeKeys=true --useLocalhostForP2P=true & 
Feb-13 15:45:43.471 [pool-1-thread-2] INFO  bisq.apitest.linux.BisqProcess: bisq-seednode -> bisq-BTC_REGTEST_Seed_2002 running with pid 11424 
Feb-13 15:45:43.476 [pool-1-thread-2] INFO  bisq.apitest.linux.BisqProcess: Log /home/serveradmin/api-beta-test/apitest/build/resources/main/bisq-BTC_REGTEST_Seed_2002/bisq.log 
Feb-13 15:45:47.990 [main] INFO  bisq.apitest.Scaffold: Giving 5000 ms for bisq-BTC_REGTEST_Arb_dao to initialize ... 
Feb-13 15:45:47.992 [pool-1-thread-3] INFO  bisq.apitest.linux.BisqProcess: Starting bisq-daemon -> bisq-BTC_REGTEST_Arb_dao ...
$ export JAVA_OPTS="-XX:MaxRAM=2g -Dlogback.configurationFile=apitest/build/resources/main/logback.xml";  /home/serveradmin/api-beta-test/bisq-daemon --appName=bisq-BTC_REGTEST_Arb_dao --appDataDir=/home/serveradmin/api-beta-test/apitest/build/resources/main/bisq-BTC_REGTEST_Arb_dao --nodePort=4444 --rpcBlockNotificationPort=5121 --rpcUser=apitest --rpcPassword=apitest --rpcPort=19443 --daoActivated=true --fullDaoNode=true --seedNodes=localhost:2002 --baseCurrencyNetwork=BTC_REGTEST --useDevPrivilegeKeys=true --useLocalhostForP2P=true --genesisBlockHeight=111 --genesisTxId=30af0050040befd8af25068cc697e418e09c2d8ebd8d411d2240591b9ec203cf --apiPassword=xyz --apiPort=9997 & 
Feb-13 15:45:52.994 [main] ERROR bisq.apitest.Scaffold:  java.lang.IllegalStateException: Error finding pid for bisq-BTC_REGTEST_Arb_dao
	at bisq.apitest.linux.BisqProcess.runBashCommand(BisqProcess.java:201)
	at bisq.apitest.linux.BisqProcess.runStartupScript(BisqProcess.java:175)
	at bisq.apitest.linux.BisqProcess.start(BisqProcess.java:82)
	at bisq.apitest.SetupTask.call(SetupTask.java:49)
	at bisq.apitest.SetupTask.call(SetupTask.java:35)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

java.lang.IllegalStateException: Error finding pid for bisq-BTC_REGTEST_Arb_dao
	at bisq.apitest.linux.BisqProcess.runBashCommand(BisqProcess.java:201)
	at bisq.apitest.linux.BisqProcess.runStartupScript(BisqProcess.java:175)
	at bisq.apitest.linux.BisqProcess.start(BisqProcess.java:82)
	at bisq.apitest.SetupTask.call(SetupTask.java:49)
	at bisq.apitest.SetupTask.call(SetupTask.java:35)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Fault: An unexpected error occurred. Please file a report at https://bisq.network/issues
java.lang.IllegalStateException: java.lang.IllegalStateException: Error finding pid for bisq-BTC_REGTEST_Arb_dao
	at bisq.apitest.Scaffold.startBisqApp(Scaffold.java:416)
	at bisq.apitest.Scaffold.startBackgroundProcesses(Scaffold.java:368)
	at bisq.apitest.Scaffold.setUp(Scaffold.java:146)
	at bisq.apitest.ApiTestMain.execute(ApiTestMain.java:66)
	at bisq.apitest.ApiTestMain.main(ApiTestMain.java:58)
Caused by: java.lang.IllegalStateException: Error finding pid for bisq-BTC_REGTEST_Arb_dao
	at bisq.apitest.linux.BisqProcess.runBashCommand(BisqProcess.java:201)
	at bisq.apitest.linux.BisqProcess.runStartupScript(BisqProcess.java:175)
	at bisq.apitest.linux.BisqProcess.start(BisqProcess.java:82)
	at bisq.apitest.SetupTask.call(SetupTask.java:49)
	at bisq.apitest.SetupTask.call(SetupTask.java:35)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

He can't find the PID of the arbdaemon if I read correctly. Any Idea what causes this? I tried on different systems and different Bitcoinversion - 22 and 24.

If you need more information or have any suggestion I would gladly appreciate.

**Comment by ghubstan** [comment]
I created a PR to fix this test harness bug:  https://github.com/bisq-network/bisq/pull/6584.

After the fix is merged, please use `bitcoind v23`.

_There are other problems with the API because work on it was suspended in Sept. 2022.  Since then, the API has not been maintained to keep up with subsequent changes to Bisq code in common with the desktop application._

**Comment by haas-ac** [comment]
That was fast!
After the PR https://github.com/bisq-network/bisq/pull/6584 was merged into the Master branch a 
`git pull`
and
`./gradlew clean build :apitest:installDaoSetup`
fixed the issue.
Thanks alot!
